eaxmple_left:
  auto-update: true
  process:
    - display: "&7Glomの神奇石头"
    - material: "stone"
    #可以被放置，破坏后会掉落原物品
    - can-be-placed: true
    - lore:
        - ""
        - "&f&m─&7&m─────────&f&m─&f介绍&f&m─&7&m─────────&f&m─"
        - ""
        - "&7一块神奇的石头，左键会有神奇的事情发生..."
        - ""
    - action:
        #动作类型，[ left / right / shift_left / shift_right / click_item / attack / build / consume / swap_to_main_hand / swap_to_offhand / right_click_entity /  break_block /  drop /  pick_up / damage ] 可通过脚本拓展
        type: left
        #执行内容
        #- 直接填内联函数  -  执行内联函数
        #- js_eval::js代码  -  执行js代码
        #- js_invoke::js文件名::函数名 - 执行js函数
        run: |-
          set loc to &entity location add listOf [ 0 3 0 ]
          set diamond to item material DIAMOND
          task in 5 {
             &diamond drop at &loc 
          }
          effect particle 'REDSTONE' at &loc data particleData dust [ color [ 255 0 255 ] in 10 ]
